name: Automatic sync of Master branch to the Escrow branch and update of json file with new version
on:
  push:
    branches:
      - master
jobs:
  Sync:
    name: sync-of-master
    runs-on: ubuntu-latest
    env:
        SOURCE_BRANCH: master
        TARGET_BRANCH: escrow
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Synchronize master and escrow_deposit branches
      run: |
        git config --global user.email "neeharika5samboji@gmail.com"
        git config --global user.name "SNeeharika"
        git checkout $TARGET_BRANCH
        git branch
        git merge $SOURCE_BRANCH
        git branch
               
    - name: update
      run: |       
        sudo apt-get install jq 
        version=$(cat deposit_information.json | jq .DepositVersion)
        ver=${version:1:-5} 

        jq '.DepositVersion |= "'"$((ver+1))"'.0.0"' deposit_information.json > tmp.$$.json && mv tmp.$$.json deposit_information.json 

        sed 's/:/ :/g' deposit_information.json > tmp.$$.json && mv tmp.$$.json deposit_information.json    
        echo $ver
        cat deposit_information.json
        git add .
        git commit -m "version updated successfully"
        git push origin $TARGET_BRANCH  
